language: ruby

sudo: false

rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - ruby-head

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - os: osx
