language: ruby

sudo: false

rvm:
  - 3.4
  - 3.3
  - 3.2
  - 3.1
  - 3.0
  - 2.7
  - 2.6
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - os: osx
      rvm: 2.7
    - os: osx
      rvm: 3.4
