#include "format.h"
#include "workbook.h"

VALUE mXlsxFormat;

#define STR2SYM(x) ID2SYM(rb_intern(x))

#define MAP_FORMAT(fmt_name, ...) {                 \
    value = rb_hash_aref(opts, STR2SYM(#fmt_name)); \
    if (!NIL_P(value))                              \
      format_set_##fmt_name(format, __VA_ARGS__);   \
  }

#define MAP_FORMATB(fmt_name) {                     \
    value = rb_hash_aref(opts, STR2SYM(#fmt_name)); \
    if (!NIL_P(value) && value)                     \
      format_set_##fmt_name(format);                \
}

void
format_apply_opts(lxw_format *format, VALUE opts) {
  VALUE value;

  MAP_FORMAT(font_name, StringValueCStr(value));
  MAP_FORMAT(font_size, NUM2INT(value))
  MAP_FORMAT(font_color, NUM2LONG(value));
  MAP_FORMATB(bold);
  MAP_FORMATB(italic);
  MAP_FORMAT(underline, NUM2LONG(value));
  MAP_FORMATB(font_strikeout);
  MAP_FORMAT(font_script, NUM2INT(value));
  MAP_FORMAT(num_format, StringValueCStr(value));
  MAP_FORMAT(num_format_index, NUM2INT(value));
  MAP_FORMATB(unlocked);
  MAP_FORMATB(hidden);
  MAP_FORMAT(align, NUM2INT(value));

  value = rb_hash_aref(opts, STR2SYM("vertical_align"));
  if (value != Qnil)
    format_set_align(format, NUM2INT(value));

  MAP_FORMATB(text_wrap);
  MAP_FORMAT(rotation, NUM2INT(value));
  MAP_FORMAT(indent, NUM2INT(value));
  MAP_FORMATB(shrink);
  MAP_FORMAT(pattern, NUM2INT(value));
  MAP_FORMAT(bg_color, NUM2LONG(value));
  MAP_FORMAT(fg_color, NUM2LONG(value));
  MAP_FORMAT(border, NUM2INT(value));
  MAP_FORMAT(bottom, NUM2INT(value));
  MAP_FORMAT(top, NUM2INT(value));
  MAP_FORMAT(left, NUM2INT(value));
  MAP_FORMAT(right, NUM2INT(value));
  MAP_FORMAT(border_color, NUM2LONG(value));
  MAP_FORMAT(bottom_color, NUM2LONG(value));
  MAP_FORMAT(top_color, NUM2LONG(value));
  MAP_FORMAT(left_color, NUM2LONG(value));
  MAP_FORMAT(right_color, NUM2LONG(value));
  MAP_FORMAT(diag_type, NUM2INT(value));
  MAP_FORMAT(diag_color, NUM2LONG(value));
  MAP_FORMAT(diag_border, NUM2INT(value));
  MAP_FORMATB(font_outline);
  MAP_FORMATB(font_shadow);
  MAP_FORMAT(font_family, NUM2INT(value));
  MAP_FORMAT(font_charset, NUM2INT(value));
  MAP_FORMAT(font_scheme, StringValueCStr(value));
  MAP_FORMATB(font_condense);
  MAP_FORMATB(font_extend);
  MAP_FORMAT(reading_order, NUM2INT(value));
  MAP_FORMAT(theme, NUM2INT(value));
}

void
init_xlsxwriter_format() {
  /* :nodoc: */
  mXlsxFormat = rb_define_module_under(mXlsxWriter, "Format");

#define MAP_LXW_FMT_CONST(name) rb_define_const(mXlsxFormat, #name, INT2NUM(LXW_##name))
  MAP_LXW_FMT_CONST(COLOR_BLACK);
  MAP_LXW_FMT_CONST(COLOR_BLUE);
  MAP_LXW_FMT_CONST(COLOR_BROWN);
  MAP_LXW_FMT_CONST(COLOR_CYAN);
  MAP_LXW_FMT_CONST(COLOR_GRAY);
  MAP_LXW_FMT_CONST(COLOR_GREEN);
  MAP_LXW_FMT_CONST(COLOR_LIME);
  MAP_LXW_FMT_CONST(COLOR_MAGENTA);
  MAP_LXW_FMT_CONST(COLOR_NAVY);
  MAP_LXW_FMT_CONST(COLOR_ORANGE);
  MAP_LXW_FMT_CONST(COLOR_PINK);
  MAP_LXW_FMT_CONST(COLOR_PURPLE);
  MAP_LXW_FMT_CONST(COLOR_RED);
  MAP_LXW_FMT_CONST(COLOR_SILVER);
  MAP_LXW_FMT_CONST(COLOR_WHITE);
  MAP_LXW_FMT_CONST(COLOR_YELLOW);

  MAP_LXW_FMT_CONST(UNDERLINE_SINGLE);
  MAP_LXW_FMT_CONST(UNDERLINE_DOUBLE);
  MAP_LXW_FMT_CONST(UNDERLINE_SINGLE_ACCOUNTING);
  MAP_LXW_FMT_CONST(UNDERLINE_DOUBLE_ACCOUNTING);

  MAP_LXW_FMT_CONST(FONT_SUPERSCRIPT);
  MAP_LXW_FMT_CONST(FONT_SUBSCRIPT);

  MAP_LXW_FMT_CONST(ALIGN_LEFT);
  MAP_LXW_FMT_CONST(ALIGN_CENTER);
  MAP_LXW_FMT_CONST(ALIGN_RIGHT);
  MAP_LXW_FMT_CONST(ALIGN_FILL);
  MAP_LXW_FMT_CONST(ALIGN_JUSTIFY);
  MAP_LXW_FMT_CONST(ALIGN_CENTER_ACROSS);
  MAP_LXW_FMT_CONST(ALIGN_DISTRIBUTED);

  MAP_LXW_FMT_CONST(ALIGN_VERTICAL_TOP);
  MAP_LXW_FMT_CONST(ALIGN_VERTICAL_BOTTOM);
  MAP_LXW_FMT_CONST(ALIGN_VERTICAL_CENTER);
  MAP_LXW_FMT_CONST(ALIGN_VERTICAL_JUSTIFY);
  MAP_LXW_FMT_CONST(ALIGN_VERTICAL_DISTRIBUTED);

  MAP_LXW_FMT_CONST(PATTERN_SOLID);
  MAP_LXW_FMT_CONST(PATTERN_MEDIUM_GRAY);
  MAP_LXW_FMT_CONST(PATTERN_DARK_GRAY);
  MAP_LXW_FMT_CONST(PATTERN_LIGHT_GRAY);
  MAP_LXW_FMT_CONST(PATTERN_DARK_HORIZONTAL);
  MAP_LXW_FMT_CONST(PATTERN_DARK_VERTICAL);
  MAP_LXW_FMT_CONST(PATTERN_DARK_DOWN);
  MAP_LXW_FMT_CONST(PATTERN_DARK_UP);
  MAP_LXW_FMT_CONST(PATTERN_DARK_GRID);
  MAP_LXW_FMT_CONST(PATTERN_DARK_TRELLIS);
  MAP_LXW_FMT_CONST(PATTERN_LIGHT_HORIZONTAL);
  MAP_LXW_FMT_CONST(PATTERN_LIGHT_VERTICAL);
  MAP_LXW_FMT_CONST(PATTERN_LIGHT_DOWN);
  MAP_LXW_FMT_CONST(PATTERN_LIGHT_UP);
  MAP_LXW_FMT_CONST(PATTERN_LIGHT_GRID);
  MAP_LXW_FMT_CONST(PATTERN_LIGHT_TRELLIS);
  MAP_LXW_FMT_CONST(PATTERN_GRAY_125);
  MAP_LXW_FMT_CONST(PATTERN_GRAY_0625);

  MAP_LXW_FMT_CONST(BORDER_THIN);
  MAP_LXW_FMT_CONST(BORDER_MEDIUM);
  MAP_LXW_FMT_CONST(BORDER_DASHED);
  MAP_LXW_FMT_CONST(BORDER_DOTTED);
  MAP_LXW_FMT_CONST(BORDER_THICK);
  MAP_LXW_FMT_CONST(BORDER_DOUBLE);
  MAP_LXW_FMT_CONST(BORDER_HAIR);
  MAP_LXW_FMT_CONST(BORDER_MEDIUM_DASHED);
  MAP_LXW_FMT_CONST(BORDER_DASH_DOT);
  MAP_LXW_FMT_CONST(BORDER_MEDIUM_DASH_DOT);
  MAP_LXW_FMT_CONST(BORDER_DASH_DOT_DOT);
  MAP_LXW_FMT_CONST(BORDER_MEDIUM_DASH_DOT_DOT);
  MAP_LXW_FMT_CONST(BORDER_SLANT_DASH_DOT);

  MAP_LXW_FMT_CONST(DIAGONAL_BORDER_UP);
  MAP_LXW_FMT_CONST(DIAGONAL_BORDER_DOWN);
  MAP_LXW_FMT_CONST(DIAGONAL_BORDER_UP_DOWN);
#undef MAP_LXW_FMT_CONST
}
